//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightCompanion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chart
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ChartType { get; set; }
        public byte[] ChartData { get; set; }
    
        public virtual ChartType ChartTypeMetadata { get; set; }
    }
}
