//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightCompanion
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightHistory
    {
        public int Id { get; set; }
        public int DepartureAirport { get; set; }
        public int ArrivalAirport { get; set; }
        public Nullable<double> TakeoffWeight { get; set; }
        public Nullable<System.TimeSpan> FlightLength { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<int> Aircraft { get; set; }
    }
}
