//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightCompanion
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightPlan
    {
        public int Id { get; set; }
        public Nullable<int> Departure { get; set; }
        public Nullable<int> Destination { get; set; }
        public string Distance { get; set; }
        public string Waypoints { get; set; }
    
        public virtual IcaoCode DestinationAirport { get; set; }
        public virtual IcaoCode DepartureAirport { get; set; }
    }
}
